// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDImi347VNZWxFu3y_lh6LR0FLo63tXUK8',
    appId: '1:787113541841:web:e6051d0b7f41923d1a45f0',
    messagingSenderId: '787113541841',
    projectId: 'nerede-yiyelim-69235',
    authDomain: 'nerede-yiyelim-69235.firebaseapp.com',
    storageBucket: 'nerede-yiyelim-69235.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADD3xoKDHlvZjyMrU8V5nN-HOZ7ONiafo',
    appId: '1:787113541841:android:2aab360223f439031a45f0',
    messagingSenderId: '787113541841',
    projectId: 'nerede-yiyelim-69235',
    storageBucket: 'nerede-yiyelim-69235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuw42S2oG7kEtSisk-N5PjvIGjpojThnw',
    appId: '1:787113541841:ios:08a65402f8d2719e1a45f0',
    messagingSenderId: '787113541841',
    projectId: 'nerede-yiyelim-69235',
    storageBucket: 'nerede-yiyelim-69235.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuw42S2oG7kEtSisk-N5PjvIGjpojThnw',
    appId: '1:787113541841:ios:08a65402f8d2719e1a45f0',
    messagingSenderId: '787113541841',
    projectId: 'nerede-yiyelim-69235',
    storageBucket: 'nerede-yiyelim-69235.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDImi347VNZWxFu3y_lh6LR0FLo63tXUK8',
    appId: '1:787113541841:web:b12694c9c990b11f1a45f0',
    messagingSenderId: '787113541841',
    projectId: 'nerede-yiyelim-69235',
    authDomain: 'nerede-yiyelim-69235.firebaseapp.com',
    storageBucket: 'nerede-yiyelim-69235.firebasestorage.app',
  );
}
